### ISSUE TITLE
[저장하기] 보드 작성 후 저장하기 시 무한로딩 현상

### ISSUE THREAD

**Issue by neoJD** [neostudio-team/GridaBoard2#367]
발견 일시 : 2022.02.04
위치 : 페이지뷰 > 저장하기

[경로]

1. 그리다보드 new 버튼 클릭

2. 새보드 생성

3. 필기 후 저장하기 클릭

발생 환경 (OS/크롬 버전) : Win 10 20H2 /  Chrome 97.0.4692.99
발생 빈도 : 항상
발생 기기 : desktop
버전 : https://gridaboard-v2-test.web.app/list
등록자 : 함종덕
사용계정 : 구글로그인(neo.jd@neolab.net)

**Comment by Minkyum-Kim** [comment]
제 PC에서는 정상적으로 동작하는거 같은데, 무한로딩시 콘솔 로그를 혹시 확인 할 수 있을까요?

**Comment by neoJD** [comment]
@Minkyum-Kim 
로그 캡쳐드립니다~!

BoardListPageFunc.tsx:678 Error adding document:  FirebaseError: Missing or insufficient permissions.
    at new e (prebuilt-47338342-439a2133.js:188:23)
    at prebuilt-47338342-439a2133.js:9963:34
    at Qn.<anonymous> (prebuilt-47338342-439a2133.js:9911:21)
    at Tt (index.esm.js:358:22)
    at Et (index.esm.js:338:50)
    at er.sa (index.esm.js:1349:33)
    at Oe (index.esm.js:693:138)
    at _e (index.esm.js:586:31)
    at me.o.Ca (index.esm.js:559:35)
    at me.o.Xa (index.esm.js:521:83) 

![log](https://user-images.githubusercontent.com/61952421/152453095-3ec03c48-7df4-4997-b307-304a833c3b82.png)

**Comment by neoJD** [comment]
테스트 서버 초기화 후 정상 동작 확인
