### ISSUE TITLE
[접근 불가] 도메인 접근 불가능한 이슈 

### ISSUE THREAD

**Issue by neoJD** [neostudio-team/GridaBoard2#375]
발견 일시 : 2022.02.07
위치 : 도메인 접근
 (https://gridaboard-v2-test.web.app/app)
설명 :

도메인 접근이 되지 않는 이슈입니다. 
아래 로그 참고 부탁드립니다. 

Failed to load resource: net::ERR_CONNECTION_REFUSED
MappingStorage.ts:640 [loading]==============================================================================================================================
MappingStorage.ts:642 [loading]..............................................................................................................................
main.bf6a082b.chunk.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'd')
    at Object.e (main.bf6a082b.chunk.js:1:53078)
    at e.dump (main.bf6a082b.chunk.js:1:14733)
    at e.loadMappingInfo (main.bf6a082b.chunk.js:1:15803)
    at Object.102 (main.bf6a082b.chunk.js:1:16790)
    at i (app:1:2996)
    at Object.32 (main.bf6a082b.chunk.js:1:448849)
    at i (app:1:2996)
    at Object.79 (main.bf6a082b.chunk.js:1:636376)
    at i (app:1:2996)
    at Object.26 (main.bf6a082b.chunk.js:1:437755)

발생 환경 (OS/크롬 버전) : Win 10 Pro 21H1 / Chrome 97.0.4692.99
발생 빈도 : 항상
발생 기기 : desktop
버전 : https://gridaboard-v2-test.web.app/list
등록자 : 함종덕
사용계정 : 구글로그인(neo.jd@neolab.net)

**Comment by Minkyum-Kim** [comment]
#376 로 해결하였습니다. 바롭 접속 가능합니다.

**Comment by neoJD** [comment]
수정 확인했습니다.
이슈 종료처리하겠습니다.
